### ISSUE TITLE
ErrorHands :  Likely missing "raise XX to YY"

### ISSUE THREAD

**Issue by Deckhole** [evolutionsoftswiss/pokernow-handhistory-converter#7]
[poker_now_log_O-p_9z9-wxUnyMfTU-EaU0wYz.csv](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/files/7315048/poker_now_log_O-p_9z9-wxUnyMfTU-EaU0wYz.csv)

This log created a lot of errors.  Let me know if there is anything I could do to help.

**Comment by evolutionsoftswiss** [comment]
I suppose the errors were coming from the player name containing a point. The point is also used with indexOf() to get the hand time without milliseconds. Additionally also on showdowns the indexOf a point was used to get the conversed showdown action. From what I've seen with your provided file, a dealer with a point in the name or winning the showdown caused the conversion errors.

Replacing those indexOf statements by lastIndexOf should correct the Issues. The code will then still find the right contents instead of finding the point from the name.

Is the potential upcoming version attached correcting the problems for you ?
[handhistory-converter-0.2.2-SNAPSHOT-program.zip](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/files/7317874/handhistory-converter-0.2.2-SNAPSHOT-program.zip)

**Comment by Deckhole** [comment]
Yeah, I was mistaken in my original comment, I thought the error file was post conversion effort.

I didn’t see that a player had a point in there name.   Thanks so much for looking into this.

I may work on a “tournament converter” that you use when there was a tournament.  Of course there would have to be a input file that contains the payouts so the results could be converted and added to the PS file.   I am using HoldemManager as the hand reader database and analysis.

Trying to figure out how to get HoldemManager to know who the hero is in the PokerNow hands because the converter doesn’t show hole cards for hero.

**Comment by Deckhole** [comment]
I thought I had done this, I’ll take a second look.  Guess I messed something up.

Thanks again!   My Java isn’t instinctual enough to rapidly follow the code.  It will take me a while to get up to speed.

Mark

**Comment by Deckhole** [comment]
Your re-mapping of names (a very nice and slick feature, btw) fixes the issue by just mapping to a name without a “.”    So I guess you replace the name before the major conversion takes place!  Very nice.

Mark
